name: Deploy

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name (e.g., service1)'
        required: true
      environment:
        description: 'Environment (dev, qa, prod)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger deploy.sh in the selected service
        run: |
          chmod +x ./${{ github.event.inputs.service }}/deploy/deploy.sh
          ./${{ github.event.inputs.service }}/deploy/deploy.sh ${{ github.event.inputs.environment }}
