name: Lint PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  pr-check:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.2'  # Use the version of Go you're working with

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.45.0/golangci-lint-1.45.0-linux-amd64.tar.gz | tar -xzv -C /tmp
          sudo mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin

      - name: Run golangci-lint
        run: |
          golangci-lint run --timeout 5m

      - name: Lint PR
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.Release_please_secret }}
        with:
          wip: false # needs write access if enabled
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with a lowercase character.

  ci:
    needs: pr-check
    strategy:
      matrix:
        service: [utils,service1, service2]
    uses: ./.github/workflows/ci.yml
    with:
      service: ${{ matrix.service }}