name: 🔁 Start Release

on:
  workflow_dispatch:

jobs:
  sync-dev-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout `dev`
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.Release_please_secret }}
          fetch-depth: 0

      - name: ⚙️ Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.Release_please_secret }}@github.com/${{ github.repository }}


      - name: 🔁 Merge `dev` into `main`
        run: |
          git fetch origin main
          git checkout main
          git merge origin/dev --no-ff -m "chore: sync dev into main"
          git push origin main
