name: Build & Deploy Service1

on:
  push:
    branches:
      - dev
    paths:
      - "service1/**"
      - ".github/workflows/service1.yml"

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    # environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Mock Build
      run: echo "🔧 Building Service1 for Dev"

    - name: Mock Deploy
      run: |
       echo "🚀 Deploying Service1 to Dev environment"
       echo "🧪 ENV MESSAGE: $ENV_MESSAGE"
      env:
        ENV_MESSAGE: ${{ vars.ENV_MESSAGE }}

