name: Build & Deploy Service1

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "../../service1/**"
      - ".github/workflows/service1.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Mock Build
      run: echo "🔧 Building Service1 for ${{ github.ref_name }}"

    - name: Mock Deploy
      run: echo "🚀 Deploying Service1 to ${{ github.ref_name }} environment"
